export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_USER_DATA_START = "GET_USER_DATA_START";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";




export const POST_ASSIGNMENT_START = "POST_ASSIGNMENT_START";
export const POST_ASSIGNMENT_SUCCESS = "POST_ASSIGNMENT_SUCCESS";
export const POST_ASSIGNMENT_FAIL = "POST_ASSIGNMENT_FAIL";

export const GET_ASSIGNMENT_START = "GET_ASSIGNMENT_START";
export const GET_ASSIGNMENT_SUCCESS = "GET_ASSIGNMENT_SUCCESS";
export const GET_ASSIGNMENT_FAIL = "GET_ASSIGNMENT_FAIL";


export const GET_DETAIL_ASSIGNMENT_START = "GET_DETAIL_ASSIGNMENT_START";
export const GET_DETAIL_ASSIGNMENT_SUCCESS = "GET_DETAIL_ASSIGNMENT_SUCCESS";
export const GET_DETAIL_ASSIGNMENT_FAIL = "GET_DETAIL_ASSIGNMENT_FAIL";

export const SUBMIT_ASSIGNMENT_START = "SUBMIT_ASSIGNMENT_START";
export const SUBMIT_ASSIGNMENT_SUCCESS = "SUBMIT_ASSIGNMENT_SUCCESS";
export const SUBMIT_ASSIGNMENT_FAIL = "SUBMIT_ASSIGNMENT_FAIL";


export const GET_GRADED_ASSIGNMENT_START = "GET_GRADED_ASSIGNMENT_START";
export const GET_GRADED_ASSIGNMENT_SUCCESS = "GET_GRADED_ASSIGNMENT_SUCCESS";
export const GET_GRADED_ASSIGNMENT_FAIL = "GET_GRADED_ASSIGNMENT_FAIL";



export const EDIT_DETAIL_ASSIGNMENT_START = "EDIT_DETAIL_ASSIGNMENT_START";
export const EDIT_DETAIL_ASSIGNMENT_SUCCESS = "EDIT_DETAIL_ASSIGNMENT_SUCCESS";
export const EDIT_DETAIL_ASSIGNMENT_FAIL = "EDIT_DETAIL_ASSIGNMENT_FAIL";

export const DELETE_ASSIGNMENT_START = "DELETE_ASSIGNMENT_START";
export const DELETE_ASSIGNMENT_SUCCESS = "DELETE_ASSIGNMENT_SUCCESS";
export const DELETE_ASSIGNMENT_FAIL = "DELETE_ASSIGNMENT_FAIL";