# Generated by Django 2.1.1 on 2020-05-06 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20200502_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.Assignment'),
        ),
    ]
